import{a as v,S as w,i as n}from"./assets/vendor-BBSqv8W6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const g=(r,t)=>{const i={params:{key:"49835598-9f74b1000f2ba2b610eab7f75",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}};return v.get("https://pixabay.com/api/",i)},y=r=>`<div class="gallery-item">
                   <a href='${r.largeImageURL}'>
                   <img src='${r.webformatURL}' alt='${r.tags}'/>
                   </a>
                  <div class='comment-box'>
                    <p class='img-comment'><b class='img-comment-title'>Likes</b>: ${r.likes}</p>
                    <p class='img-comment'><b class='img-comment-title'>Views</b>: ${r.views}</p>
                    <p class='img-comment'><b class='img-comment-title'>Comments</b>: ${r.comments}</p>
                    <p class='img-comment'><b class='img-comment-title'>Downloads</b>: ${r.downloads}</p>
                  </div>
                </div>`,b=document.querySelector(".user-search"),h=document.querySelector("#input-search"),l=document.querySelector("#results"),f=document.querySelector("#loader-js"),s=document.querySelector(".js-load-more-btn");let c=1,d="",u=0,L=new w(".gallery a",{captionsData:"alt",captionDelay:250});const S=async r=>{if(r.preventDefault(),d=h.value.trim(),!d){s.classList.add("is-hidden"),n.error({title:"Error",message:"The search field cannot be empty. Please try again!",position:"topRight"});return}l.innerHTML="",h.value="",f.classList.remove("hidden"),c=1,s.classList.add("is-hidden");try{const{data:t}=await g(d,c);if(t.hits.length===0){n.warning({title:"No results",message:"No images found for your query!",position:"topRight"});return}l.innerHTML=t.hits.map(y).join(""),L.refresh(),window.scrollTo({top:l.offsetTop,behavior:"smooth"}),u=Math.ceil(t.totalHits/15),u>1?(s.classList.remove("is-hidden"),s.removeEventListener("click",p),s.addEventListener("click",p)):s.classList.add("is-hidden")}catch(t){n.error({title:"Error",message:"An error occurred. Please try again!",position:"topRight"}),console.error(t)}finally{f.classList.add("hidden"),b.reset()}},p=async r=>{c++;try{const{data:t}=await g(d,c),i=t.hits.map(y).join("");l.insertAdjacentHTML("beforeend",i),L.refresh();const a=document.querySelector(".gallery-item");if(a){const e=a.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}c>=u&&(s.classList.add("is-hidden"),n.warning({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}),s.removeEventListener("click",p))}catch(t){console.error(t),n.error({title:"Error",message:"Failed to load more images!",position:"topRight"})}};b.addEventListener("submit",S);
//# sourceMappingURL=index.js.map
