import{a as v,S as w,i as a}from"./assets/vendor-BBSqv8W6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&i(m)}).observe(document,{childList:!0,subtree:!0});function d(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=d(e);fetch(e.href,o)}})();const g=(r,t=1)=>v.get("https://pixabay.com/api/",{params:{key:"49835598-9f74b1000f2ba2b610eab7f75",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}}),y=r=>`
  <li class="gallery-item">
    <a href="${r.largeImageURL}">
      <img src="${r.webformatURL}" alt="${r.tags}" />
    </a>
    <div class="comment-box">
      <p class="img-comment"><b>Likes:</b> ${r.likes}</p>
      <p class="img-comment"><b>Views:</b> ${r.views}</p>
      <p class="img-comment"><b>Comments:</b> ${r.comments}</p>
      <p class="img-comment"><b>Downloads:</b> ${r.downloads}</p>
    </div>
  </li>`,b=document.querySelector(".form"),h=document.querySelector(".input-search"),c=document.querySelector(".gallery"),f=document.querySelector(".loader"),s=document.querySelector(".js-load-more-btn");let n=1,l="",u=0,L=new w(".gallery a",{captionsData:"alt",captionDelay:250});const S=async r=>{if(r.preventDefault(),l=h.value.trim(),!l){s.classList.add("is-hidden"),a.error({title:"Error",message:"The search field cannot be empty. Please try again!",position:"topRight"});return}c.innerHTML="",h.value="",f.classList.remove("hidden"),n=1,s.classList.add("is-hidden");try{const{data:t}=await g(l,n);if(t.hits.length===0){a.warning({title:"No results",message:"No images found for your query!",position:"topRight"});return}c.innerHTML=t.hits.map(y).join(""),L.refresh(),window.scrollTo({top:c.offsetTop,behavior:"smooth"}),u=Math.ceil(t.totalHits/15),u>1?(s.classList.remove("is-hidden"),s.removeEventListener("click",p),s.addEventListener("click",p)):s.classList.add("is-hidden")}catch(t){a.error({title:"Error",message:"An error occurred. Please try again!",position:"topRight"}),console.error(t)}finally{f.classList.add("hidden"),b.reset()}},p=async r=>{n++;try{const{data:t}=await g(l,n),d=t.hits.map(y).join("");c.insertAdjacentHTML("beforeend",d),L.refresh();const i=document.querySelector(".gallery-item");if(i){const e=i.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}n>=u&&(s.classList.add("is-hidden"),a.warning({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}),s.removeEventListener("click",p))}catch(t){console.error(t),a.error({title:"Error",message:"Failed to load more images!",position:"topRight"})}};b.addEventListener("submit",S);
//# sourceMappingURL=index.js.map
